drop table if exists task_domain CASCADE;
drop table if exists to_do_domain CASCADE;
create table task_domain (id bigint generated by default as identity, category varchar(255), completed boolean, name varchar(255), rank integer, my_to_do_id bigint, primary key (id));
create table to_do_domain (id bigint generated by default as identity, list_name varchar(255), primary key (id));